app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from app import views

urlpatterns = [
    # Admin com Django Admin
    path('admin/', admin.site.urls),

    # Autenticação
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # API
    path('api/v1/', include('authentication.urls')),

    # Aplicações do sistema
    path('users/', include('users.urls')),
    path('brands/', include('brands.urls')),
    path('categories/', include('categories.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('inflows/', include('inflows.urls')),
    path('outflows/', include('outflows.urls')),
    path('products/', include('products.urls')),
    path('reports/', include('reports.urls')),

    # Página inicial e Termos de Uso
    path('', views.home, name='home'),
    path('terms_use/', views.terms_use, name='terms_use'),
]

brands/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=500)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    first_name = None
    last_name = None
    date_joined = None
    username = models.CharField(verbose_name="Nome de Usuário", max_length=255, unique=True)
    full_name = models.CharField(verbose_name="Nome Completo", max_length=255)
    email = models.EmailField(verbose_name="E-mail", max_length=255, unique=True)
    cpf = models.CharField(verbose_name="CPF", max_length=11, unique=True)
    phone_number = models.CharField(verbose_name="Contato", max_length=15, unique=True)
    birth_date = models.DateField(verbose_name="Data de Nascimento", null=True, blank=True)
    created_at = models.DateTimeField(verbose_name="Criado em", auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name="Atualizado em", auto_now=True)
    is_active = models.BooleanField(verbose_name="Ativo", default=True)
    is_staff = models.BooleanField(verbose_name="Administrador", default=False)
    is_superuser = models.BooleanField(verbose_name="Superusuário", default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'full_name', 'cpf']

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"
        db_table = 'users'

    def __str__(self):
        return f"{self.email} | {self.full_name} | {self.cpf}"

inflows/views.py
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from rest_framework import generics

from inflows import forms, models, serializers


class InflowListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Inflow
    template_name = 'inflow_list.html'
    context_object_name = 'inflows'
    paginate_by = 10
    permission_required = 'inflows.view_inflow'

    def get_queryset(self):
        queryset = super().get_queryset()
        product = self.request.GET.get('product')

        if product:
            queryset = queryset.filter(product__title__icontains=product)

        return queryset


class InflowCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = models.Inflow
    template_name = 'inflow_create.html'
    form_class = forms.InflowForm
    success_url = reverse_lazy('inflow_list')
    permission_required = 'inflows.add_inflow'


class InflowDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Inflow
    template_name = 'inflow_detail.html'
    permission_required = 'inflows.view_inflow'


class InflowCreateListAPIView(generics.ListCreateAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer


class InflowRetrieveAPIView(generics.RetrieveAPIView):
    queryset = models.Inflow.objects.all()
    serializer_class = serializers.InflowSerializer

app/templates/components/partials/footer.html
<footer class="footer mt-auto py-2 text-center border-top bg-body-tertiary">
  <div class="container d-flex justify-content-center align-items-center gap-3 flex-wrap">
    <p class="mb-0 text-body-secondary d-flex align-items-center">
      © 2025 <strong class="ms-1">Data Storage</strong>. Todos os direitos reservados.
    </p>
    <div class="d-flex align-items-center gap-3">
      <a href="https://facebook.com" target="_blank" class="text-body-secondary fs-4">
        <i class="fab fa-facebook"></i>
      </a>
      <a href="https://instagram.com" target="_blank" class="text-body-secondary fs-4">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="https://linkedin.com" target="_blank" class="text-body-secondary fs-4">
        <i class="fab fa-linkedin"></i>
      </a>
    </div>
  </div>
</footer>

app/templates/components/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
<link rel="icon" href="{% static 'img/box-open-solid.svg' %}" type="image/svg+xml">
<title>{% block title %}Data Storage{% endblock %}</title>

app/templates/components/partials/header.html
<nav class="navbar border-bottom bg-body-tertiary">
  <div class="container-fluid py-2">
    <div class="d-flex align-items-center">
      {% if user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% include 'components/partials/sidebar.html' %}
      {% endif %}  
      <div class="text-content ms-3">
        <a class="navbar-brand" href="{% url 'home' %}">
          <i class="fa-solid fa-box-open"></i> 
          <span class="ms-1">Data Storage</span>
        </a>
      </div>
    </div>
    <div class="d-flex align-items-center gap-3">
      {% include 'components/partials/theme_toggle.html' %}
      {% include 'components/partials/user_menu.html' %}
    </div>
  </div>
</nav>
{% include 'components/partials/logout_modal.html' %}

app/templates/components/partials/logout_modal.html
<div class="modal fade" id="confirmLogoutModal" tabindex="-1" aria-labelledby="confirmLogoutModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header border-0">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center">
        <div class="icon-content fa-5x">
          <i class="fa-solid fa-circle-exclamation"></i>
        </div>
        <div class="text-content mt-1">
          <p>Deseja realmente sair?</p>
        </div>
      </div>
      <div class="modal-footer justify-content-center border-0">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
        <form id="logoutForm" method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Sair</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/templates/components/partials/pagination.html
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            Primeira
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Anterior
          </a>
        </li>
      {% endif %}
      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
          {% if page_obj.number == page_number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">
                {{ page_number }}
              </a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Próxima
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Última
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

app/templates/components/partials/scripts.html
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/chart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/color_mode.js' %}"></script>
<script type="text/javascript" src="{% static 'js/fontawesome.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pdf_generate.js' %}"></script>
<script type="text/javascript" src="{% static 'js/groups_func.js' %}"></script>

app/templates/components/partials/sidebar.html
<div class="offcanvas offcanvas-start bg-body-tertiary" tabindex="-1" id="offcanvasNavbarDark" aria-labelledby="offcanvasNavbarDarkLabel">
  <div class="offcanvas-header border-bottom" id="offcanvas-header-custom">
    <div class="text-content ms-4 py-1">
      <a class="navbar-brand" href="{% url 'home' %}">
        <i class="fa-solid fa-box-open"></i> 
        <span class="ms-1">Data Storage</span>
      </a>
    </div>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="container-fluid">
      <div class="nav flex-column align-items-start">
        <div class="nav-item">
          <a href="{% url 'home' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
            <i class="fa-solid fa-gauge-high"></i>
            <span class="ms-1 fs-5">Dashboard</span>
          </a>
        </div>
        {% if perms.suppliers.view_supplier %}
          <div class="nav-item">
            <a href="{% url 'supplier_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-truck"></i>
              <span class="ms-1 fs-5">Fornecedores</span>
            </a>
          </div>
        {% endif %}   
        {% if perms.brands.view_brand %}
          <div class="nav-item">
            <a href="{% url 'brand_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-shop"></i>
              <span class="ms-1 fs-5">Marcas</span>
            </a>
          </div>
        {% endif %}
        {% if perms.categories.view_category %}  
          <div class="nav-item">
            <a href="{% url 'category_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-tags"></i>
              <span class="ms-1 fs-5">Categorias</span>
            </a>
          </div>
        {% endif %}
        {% if perms.products.view_product %}  
          <div class="nav-item">
            <a href="{% url 'product_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-box"></i>
              <span class="ms-1 fs-5">Produtos</span>
            </a>
          </div>
        {% endif %}
        {% if perms.inflows.view_inflow %}  
          <div class="nav-item">
            <a href="{% url 'inflow_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-square-plus"></i>
              <span class="ms-1 fs-5">Entradas</span>
            </a>
          </div>
        {% endif %}
        {% if perms.outflows.view_outflow %}  
          <div class="nav-item">
            <a href="{% url 'outflow_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-arrow-up-right-from-square"></i>
              <span class="ms-1 fs-5">Saídas</span>
            </a>
          </div>
        {% endif %}
        {% if perms.users.view_user %}
          <div class="nav-item">
            <a href="{% url 'user_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-users"></i>
              <span class="ms-1 fs-5">Usuários</span>
            </a>
          </div>
        {% endif %}
        {% if perms.reports.view_report %} 
          <div class="nav-item">
            <a href="{% url 'report_list' %}" class="nav-link ms-3 fs-5 px-0 align-middle">
              <i class="fa-solid fa-file-lines"></i>
              <span class="ms-1 fs-5">Relatórios</span>
            </a>
          </div>
        {% endif %}    
      </div>
    </div>  
  </div>
</div>

app/templates/components/partials/terms_use.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-5">
  <div class="card shadow-lg border-0">
    <div class="card-header bg-primary text-white text-center py-4">
      <h1 class="display-5">Termos de Uso</h1>
    </div>
    <div class="card-body px-4 py-5">
      <p class="fs-5 text-justify">
        O <strong>DataStorage</strong> é um sistema de gerenciamento de estoque desenvolvido para resolver as dificuldades
        enfrentadas por pequenas e médias empresas em manter um controle preciso e centralizado de estoques, fornecedores
        e produtos. Este sistema oferece uma plataforma acessível e intuitiva para simplificar o gerenciamento de mercadorias.
      </p>
      <p class="fs-5 text-justify">
        Nosso objetivo é fornecer ferramentas que permitem cadastrar e controlar fornecedores, marcas, categorias e produtos,
        além de funcionalidades para registrar vendas, calcular lucros e gerenciar movimentações de estoque de forma eficaz.
      </p>
      <div class="text-center mt-4">
        <a href="{% url 'home' %}" class="btn btn-secondary btn-lg">
          <i class="fas fa-arrow-left me-2"></i>Voltar
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/components/partials/theme_toggle.html
<div class="dropdown">
  <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
          id="bd-theme"
          type="button"
          aria-expanded="false"
          data-bs-toggle="dropdown"
          aria-label="Toggle theme (auto)">
    <i class="fas fa-adjust my-1 theme-icon-active"></i>
    <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow bg-body-tertiary" aria-labelledby="bd-theme-text">
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
        <i class="fas fa-sun me-2 opacity-50"></i>
        Light
        <i class="fas fa-check ms-auto d-none"></i>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
        <i class="fas fa-moon me-2 opacity-50"></i>
        Dark
        <i class="fas fa-check ms-auto d-none"></i>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
        <i class="fas fa-adjust me-2 opacity-50"></i>
        Auto
        <i class="fas fa-check ms-auto d-none"></i>
      </button>
    </li>
  </ul>
</div>

app/templates/components/partials/user_menu.html
<div class="justify-content-end">
  {% if user.is_authenticated %}
    <div class="btn-group dropstart">
      <button type="button" class="btn btn-outline-primary dropdown-toggle me-2 py-2 rounded" data-bs-toggle="dropdown" aria-expanded="false">
        {{ request.user.username }}
      </button>
      <ul class="dropdown-menu justify-content-end bg-body-tertiary">
        <li><a class="dropdown-item dropdown-item-icon" href="{% url 'user_detail' request.user.id %}"><i class="fa-solid fa-circle-user"></i> Meus dados</a></li>
        <li><a class="dropdown-item dropdown-item-icon" href="{% url 'terms_use' %}"><i class="fa-solid fa-file-lines"></i> Termos de uso</a></li>
        <li><hr class="dropdown-divider"></li>
        <li>
          <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#confirmLogoutModal">
            <i class="fa-solid fa-circle-xmark"></i> Sair
          </button>
        </li>
      </ul>  
    </div>
  {% endif %}      
</div>