app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from app import views

urlpatterns = [
    # Admin com Django Admin
    path('admin/', admin.site.urls),

    # Autenticação
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # API
    path('api/v1/', include('authentication.urls')),

    # Aplicações do sistema
    path('users/', include('users.urls')),
    path('brands/', include('brands.urls')),
    path('categories/', include('categories.urls')),
    path('suppliers/', include('suppliers.urls')),
    path('inflows/', include('inflows.urls')),
    path('outflows/', include('outflows.urls')),
    path('products/', include('products.urls')),
    path('reports/', include('reports.urls')),

    # Página inicial e Termos de Uso
    path('', views.home, name='home'),
    path('terms_use/', views.terms_use, name='terms_use'),
]

inflows/models.py
from django.db import models
from products.models import Product
from suppliers.models import Supplier


class Inflow(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT, related_name='inflows')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='inflows')
    quantity = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return str(self.product)

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="auto">
  <head>
    {% include 'components/partials/head.html' %}
  </head>
  <body>
    <div id="main-container">
      {% include 'components/partials/header.html' %}
      <div class="container mt-4">
        <div class="container-fluid py-3">
          <main>
            {% block content %}
            {% endblock %}
          </main>
        </div>
      </div>
      {% include 'components/partials/footer.html' %}
    </div>
    {% include 'components/partials/scripts.html' %}
  </body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
  {% if perms.products.view_product and perms.inflows.view_inflow %}
    {% include 'components/product_metrics.html' %}
  {% endif %}
  <div class="mb-4"></div>
  {% if perms.outflows.view_outflow %}
    {% include 'components/sales_metrics.html' %}
  {% endif %}
  {% if perms.outflows.view_outflow %}
    <div class="row mt-4 justify-content-center">
      <div class="col-md-6 text-center">
        <h5 class="text-center mb-3">Valor de vendas (Últimos 7 Dias)</h5>
        <canvas id="dailySalesChart"></canvas>
      </div>
      <div class="col-md-6 text-center">
        <h5 class="text-center mb-3">Quantidade de Vendas Diárias</h5>
        <canvas id="dailySalesQuantityChart"></canvas>
      </div>
      <script>
        document.addEventListener("DOMContentLoaded", function() {
          var dailySalesData = JSON.parse('{{ daily_sales_data|safe }}');
          var dailySalesQuantityData = JSON.parse('{{ daily_sales_quantity_data|safe }}');
    
          var ctxDailySales = document.getElementById('dailySalesChart').getContext('2d');
          var dailySalesChart = new Chart(ctxDailySales, {
            type: 'line',
            data: {
              labels: dailySalesData.dates,
              datasets: [{
                label: 'Valor em vendas',
                data: dailySalesData.values,
                fill: false,
                borderColor: 'rgba(54, 162, 235, 1)',
                borderWidth: 2,
                tension: 0.5
              }]
            },
            options: {
              scales: {
                y: {
                  beginAtZero: true
                }
              }
            }
          });
    
          var ctxDailySalesQuantity = document.getElementById('dailySalesQuantityChart').getContext('2d');
          var dailySalesQuantityChart = new Chart(ctxDailySalesQuantity, {
            type: 'bar',
            data: {
              labels: dailySalesQuantityData.dates,
              datasets: [{
                label: 'Quantidade de Vendas',
                data: dailySalesQuantityData.values,
                backgroundColor: 'rgba(255, 99, 132, 0.6)',
                borderColor: 'rgba(255, 99, 132, 1)',
                borderWidth: 1
              }]
            },
            options: {
              scales: {
                y: {
                  beginAtZero: true
                }
              }
            }
          });
        });
      </script>
    </div>
  {% endif %}
  {% if perms.products.view_product %}
    <div class="row mt-5 justify-content-center">
      <div class="col-md-6 text-center">
        <h5 class="mb-3">Produtos por Categoria</h5>
        <div class="mb-4"></div>
        <div class="embed-responsive embed-responsive-1by1" style="width: 400px; display: inline-block;">
          <canvas id="productByCategoryChart" class="embed-responsive-item"></canvas>
        </div>
      </div>
      <div class="col-md-6 text-center">
        <h5 class="mb-3">Produtos por Marca</h5>
        <div class="mb-4"></div>
        <div style="width: 400px; display: inline-block;">
          <canvas id="productByBrandChart" class="embed-responsive-item"></canvas>
        </div>
      </div>
      <script>
        document.addEventListener("DOMContentLoaded", function() {  
          var productCountByCategory = JSON.parse('{{ product_count_by_category|safe }}');
          var productCountByBrand = JSON.parse('{{ product_count_by_brand|safe }}');
    
          var ctxCategory = document.getElementById('productByCategoryChart').getContext('2d');
          var productByCategoryChart = new Chart(ctxCategory, {
            type: 'doughnut',
            data: {
              labels: Object.keys(productCountByCategory),
              datasets: [{
                data: Object.values(productCountByCategory),
                borderWidth: 1
              }]
            },
            options: {
              plugins: {
                legend: {
                  display: false
                },
              }
            }
          });
    
          var ctxBrand = document.getElementById('productByBrandChart').getContext('2d');
          var productByBrandChart = new Chart(ctxBrand, {
            type: 'doughnut',
            data: {
              labels: Object.keys(productCountByBrand),
              datasets: [{
                data: Object.values(productCountByBrand),
                borderWidth: 1
              }]
            },
            options: {
              plugins: {
                legend: {
                  display: false
                },
              }
            }
          });
        });
      </script>
    </div>
  {% endif %}  
{% endblock  %}